server:
    port: 9097

spring:
    datasource:
        url: jdbc:oracle:thin:@192.168.1.1:1521:ee
        username: username
        password: password

mybatis:
    mapper-locations: classpath:mappers/*/*.xml